### ISSUE TITLE
No playback device available, click to open spotify!

### ISSUE THREAD

**Issue by amiwrpremiumold** [MartijnVogelaar/krunner-spotify#4]
Although I have opened Spotify desktop app and Spotify web player, still I get this message

![Screenshot_20201126_224314](https://user-images.githubusercontent.com/39862677/100386149-d7663180-3039-11eb-9fac-292387aeda7e.png)

**Comment by MartijnVogelaar** [comment]
I'm sorry for the late reply I totally missed out on your issue report. It is most likely caused by the fact that neither the spotify desktop app nor the spotify client in the browser is actually "registered" as a playback device. You'll need to start playing on either one of them in order to become a "playback" device. 

After pausing a playback device and not playing music it will "unregister" as playback device eventually.

Unfortunately this is how spotify and its API work, at the moment there is nothing I can do about it.


--------------------Edit----------------------

I've looked into this a bit further, there is a possibility to automatically start playing using direct links for the spotify webplayer. I've put this on my backlog and will be implemented in a month or so.

**Comment by amiwrpremiumold** [comment]
Thanks, fixed
